basePath: /api/v1
definitions:
  models.Result:
    properties:
      message:
        type: string
      place:
        type: string
      success:
        type: boolean
    type: object
  models.UserPublicInfo:
    properties:
      bestScore:
        type: string
      bestTime:
        type: string
      email:
        type: string
      name:
        type: string
    type: object
host: https://escapade-backend.herokuapp.com
info:
  contact: {}
  description: Documentation
  license: {}
  title: Escapade API
  version: "1.0"
paths:
  /users/{name}/profile:
    get:
      description: return public information, such as name or best_score
      operationId: GetProfile
      parameters:
      - description: Profile email
        in: path
        name: email
        type: string
      - description: Profile nickname
        in: path
        name: nickname
        type: string
      responses:
        "200":
          description: Profile found successfully
          schema:
            $ref: '#/definitions/models.UserPublicInfo'
            type: object
        "400":
          description: Invalid username
          schema:
            $ref: '#/definitions/models.Result'
            type: object
        "404":
          description: User not found
          schema:
            $ref: '#/definitions/models.Result'
            type: object
      summary: Get some of user fields
swagger: "2.0"
